POST http://localhost:3003/signup
Content-Type: application/json

{
    "name": "Rafael Silva",
    "email": "rafael@labechef.com.br",
    "password": "123456"
}

###

POST http://localhost:3003/login
Content-Type: application/json

{
    "email": "bruno@labechef.com.br",
    "password": "qwerty"
}

###

GET http://localhost:3003/user/profile
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImVhYTA4MDlkLWJiOTYtNGJiNi1hNTUwLTMzNmRkMjNjOTZlYiIsImlhdCI6MTYxNzk3NDQ2NywiZXhwIjoxNjE4MDYwODY3fQ.0VbN97AdAa00ykGl-Jh4ZVP_2ZeHgCjbepySJ5lKROk