PUT   http://localhost:3003/user 
Content-Type: application/json

{
	"name": "Bruno Silva",
	"nickname": "Brunohcs",
	"email": "silva@dev.com"
}

###

GET http://localhost:3003/user/user1616779034606

###

POST http://localhost:3003/user/edit/user1616779034606
Content-Type: application/json

{
	"name": "Astro Dev"
}

###

PUT http://localhost:3003/task 
Content-Type: application/json

{
	"title": "Terminar endpoint 5",
	"description": "Criar o o endpoint de criação de tarefas da aplicação",
	"scheduleDate": "26/03/2021",
	"creatorUserId": "user1616795673606" 
}

###

GET http://localhost:3003/task/user1616795673606