POST http://localhost:3003/user/signup
Content-Type: application/json

{
    "email":"bruno2@dev.com",
    "password": "abc123"
}

###
GET http://localhost:3003/userByemail
Content-Type: application/json

{
    "email": "camila@dev.com"
}

###

POST  http://localhost:3003/user/login
Content-Type: application/json

{
    "email": "camila@dev.com",
    "password": "qwerty"
}